name: nylo_support
description: Support library for the Nylo framework. This library supports routing, widgets, localization, cli, storage and more.
version: 5.60.0
homepage: https://nylo.dev
repository: https://github.com/nylo-core/support/tree/5.x
issue_tracker: https://github.com/nylo-core/support/issues
documentation: https://github.com/nylo-core/support
funding:
  - https://github.com/sponsors/agordn52
topics:
  - micro-framework
  - framework

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  page_transition: ^2.1.0
  flutter_secure_storage: ^9.0.0
  flutter_dotenv: ^5.1.0
  theme_provider: ^0.6.0
  validated: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.4.2
  recase: ^4.1.0
  get_time_ago: ^1.3.1
  flutter_styled_toast: ^2.2.1
  animate_do: ^3.3.4
  pull_to_refresh_flutter3: ^2.0.2
  equatable: ^2.0.5
  rxdart: ^0.27.7
  pretty_dio_logger: ^1.3.1
  intl: ^0.18.1
  skeletonizer: ^1.1.1
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

screenshots:
  - description: The Nylo package logo.
    path: screenshots/logo.png

# The following section is specific to Flutter.
flutter:
